// ============================================================
// QUESTION BANK — Minna no Nihongo Lessons 26-28
// Each question: { id, type, category, difficulty, sentence, ask, options, correct, exp, grammarPoint }
// ============================================================

const QUESTION_BANK = [

// ── KANJI READING ─────────────────────────────────────────
{id:'k001',type:'kanji',category:'漢字',difficulty:'easy',
 s:'自分で旅行を計画するのは楽しいです。',a:'「自分」の読み方は？',
 o:['じぶん','ちっぷん','じっぷん','ちぶん'],c:0,exp:'自分 = じぶん (oneself)'},
{id:'k002',type:'kanji',category:'漢字',difficulty:'easy',
 s:'自分で旅行を計画するのは楽しいです。',a:'「旅行」の読み方は？',
 o:['りゅうこ','りょうこ','りょこう','りゅこう'],c:2,exp:'旅行 = りょこう (travel)'},
{id:'k003',type:'kanji',category:'漢字',difficulty:'medium',
 s:'自分で旅行を計画するのは楽しいです。',a:'「計画」の読み方は？',
 o:['けいかく','けいが','げいかく','けが'],c:0,exp:'計画 = けいかく (plan)'},
{id:'k004',type:'kanji',category:'漢字',difficulty:'easy',
 s:'自分で旅行を計画するのは楽しいです。',a:'「楽しい」の読み方は？',
 o:['うれしい','うつくしい','たのしい','いそがしい'],c:2,exp:'楽しい = たのしい (fun, enjoyable)'},
{id:'k005',type:'kanji',category:'漢字',difficulty:'medium',
 s:'この学生は毎日地下鉄で大学に通っています。',a:'「地下鉄」の読み方は？',
 o:['じげてつ','じがてつ','ちげてつ','ちかてつ'],c:3,exp:'地下鉄 = ちかてつ (subway)'},
{id:'k006',type:'kanji',category:'漢字',difficulty:'easy',
 s:'この学生は毎日地下鉄で大学に通っています。',a:'「大学」の読み方は？',
 o:['たいがく','だいかく','たいかく','だいがく'],c:3,exp:'大学 = だいがく (university)'},
{id:'k007',type:'kanji',category:'漢字',difficulty:'medium',
 s:'この学生は毎日地下鉄で大学に通っています。',a:'「通って」の読み方は？',
 o:['かえって','かよって','かおって','いって'],c:1,exp:'通う = かよう (to commute)'},
{id:'k008',type:'kanji',category:'漢字',difficulty:'easy',
 s:'姉がいつも食事の用意をしてくれます。',a:'「姉」の読み方は？',
 o:['いもうと','おとうと','あね','あに'],c:2,exp:'姉 = あね (older sister)'},
{id:'k009',type:'kanji',category:'漢字',difficulty:'medium',
 s:'姉がいつも食事の用意をしてくれます。',a:'「食事」の読み方は？',
 o:['しょくじ','しょうじ','そうじ','そくじ'],c:0,exp:'食事 = しょくじ (meal)'},
{id:'k010',type:'kanji',category:'漢字',difficulty:'medium',
 s:'姉がいつも食事の用意をしてくれます。',a:'「用意」の読み方は？',
 o:['よい','ようい','よじ','ようじ'],c:1,exp:'用意 = ようい (preparation)'},
{id:'k011',type:'kanji',category:'漢字',difficulty:'medium',
 s:'彼女はこうちょくしたようにうごかない。',a:'「うごかない」の漢字は？',
 o:['動かない','働かない','重かない','衝かない'],c:0,exp:'動く = うごく (to move)'},
{id:'k012',type:'kanji',category:'漢字',difficulty:'hard',
 s:'奈良と京都は日本の古い都です。',a:'「都」の読み方は？',
 o:['みなと','ふるさと','みやこ','いなか'],c:2,exp:'都 = みやこ (capital city)'},
{id:'k013',type:'kanji',category:'漢字',difficulty:'easy',
 s:'趣味としてじゅうどうを習うつもりです。',a:'「趣味」の読み方は？',
 o:['しゅみ','きょうみ','ちゅみ','ちょうみ'],c:0,exp:'趣味 = しゅみ (hobby)'},
{id:'k014',type:'kanji',category:'漢字',difficulty:'medium',
 s:'きゅうに空が暗くなりました。',a:'「きゅうに」の漢字は？',
 o:['早に','速に','突に','急に'],c:3,exp:'急に = きゅうに (suddenly)'},
{id:'k015',type:'kanji',category:'漢字',difficulty:'hard',
 s:'兄が入院したので、花を持ってお見舞いに行った。',a:'「お見舞い」の読み方は？',
 o:['おみあい','おみまい','おけんまい','おけんあい'],c:1,exp:'お見舞い = おみまい (hospital visit)'},
{id:'k016',type:'kanji',category:'漢字',difficulty:'hard',
 s:'のどがかわいています。水が飲みたいです。',a:'「かわいて」の漢字は？',
 o:['乾いて','変いて','掛いて','渇いて'],c:3,exp:'渇く = かわく (to be thirsty) ≠ 乾く (to dry out)'},
{id:'k017',type:'kanji',category:'漢字',difficulty:'easy',
 s:'先生の奥さんはとても優しいです。',a:'「優しい」の読み方は？',
 o:['きびしい','やさしい','たのしい','したしい'],c:1,exp:'優しい = やさしい (kind, gentle)'},
{id:'k018',type:'kanji',category:'漢字',difficulty:'medium',
 s:'ディズニーランドで姉に人形を買ってやった。',a:'「人形」の読み方は？',
 o:['にんけい','じんけい','にんぎょう','じんぎょう'],c:2,exp:'人形 = にんぎょう (doll)'},
{id:'k019',type:'kanji',category:'漢字',difficulty:'hard',
 s:'おばあさんが昔のいろんな物語を話してくれた。',a:'「物語」の読み方は？',
 o:['ものはなし','ものばなし','ものかたり','ものがたり'],c:3,exp:'物語 = ものがたり (story, tale)'},
{id:'k020',type:'kanji',category:'漢字',difficulty:'medium',
 s:'友達がいなくて、さびしいです。',a:'「さびしい」の漢字は？',
 o:['悲しい','厳しい','美しい','寂しい'],c:3,exp:'寂しい = さびしい (lonely)'},
{id:'k021',type:'kanji',category:'漢字',difficulty:'easy',
 s:'海から強い風がふいてきた。',a:'「海」の読み方は？',
 o:['うみ','あめ','かぜ','うた'],c:0,exp:'海 = うみ (sea, ocean)'},
{id:'k022',type:'kanji',category:'漢字',difficulty:'easy',
 s:'海から強い風がふいてきた。',a:'「強い」の読み方は？',
 o:['おもい','あまい','すごい','つよい'],c:3,exp:'強い = つよい (strong)'},
{id:'k023',type:'kanji',category:'漢字',difficulty:'easy',
 s:'海から強い風がふいてきた。',a:'「風」の読み方は？',
 o:['かべ','かばん','かぜ','かぎ'],c:2,exp:'風 = かぜ (wind)'},
{id:'k024',type:'kanji',category:'漢字',difficulty:'easy',
 s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「魚」の読み方は？',
 o:['こめ','さかな','にく','やさい'],c:1,exp:'魚 = さかな (fish)'},
{id:'k025',type:'kanji',category:'漢字',difficulty:'medium',
 s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「夕飯」の読み方は？',
 o:['ちゅうはん','ゆうはん','ちゅうしょく','ゆうしょく'],c:1,exp:'夕飯 = ゆうはん (dinner, evening meal)'},
{id:'k026',type:'kanji',category:'漢字',difficulty:'easy',
 s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「使った」の読み方は？',
 o:['つかった','つくった','はって','きった'],c:0,exp:'使う = つかう (to use)'},
{id:'k027',type:'kanji',category:'漢字',difficulty:'easy',
 s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「料理」の読み方は？',
 o:['りょり','りょいり','りょうり','りょおい'],c:2,exp:'料理 = りょうり (cooking, dish)'},
{id:'k028',type:'kanji',category:'漢字',difficulty:'medium',
 s:'となりの教室から歌が聞こえるので、まどを閉めてください。',a:'「教室」の読み方は？',
 o:['きょうじつ','きゅうしつ','きゅうじつ','きょうしつ'],c:3,exp:'教室 = きょうしつ (classroom)'},
{id:'k029',type:'kanji',category:'漢字',difficulty:'easy',
 s:'となりの教室から歌が聞こえるので、まどを閉めてください。',a:'「歌」の読み方は？',
 o:['うた','おた','きえ','こえ'],c:0,exp:'歌 = うた (song)'},
{id:'k030',type:'kanji',category:'漢字',difficulty:'medium',
 s:'となりの教室から歌が聞こえるので、まどを閉めてください。',a:'「閉めて」の読み方は？',
 o:['あめて','とめて','しめて','やめて'],c:2,exp:'閉める = しめる (to close)'},
// Extra kanji for variety
{id:'k031',type:'kanji',category:'漢字',difficulty:'medium',
 s:'毎朝、新聞を読んでから会社に行きます。',a:'「新聞」の読み方は？',
 o:['しんもん','しんぶん','にゅうもん','にゅうぶん'],c:1,exp:'新聞 = しんぶん (newspaper)'},
{id:'k032',type:'kanji',category:'漢字',difficulty:'medium',
 s:'毎朝、新聞を読んでから会社に行きます。',a:'「会社」の読み方は？',
 o:['かいしゃ','かいさ','がいしゃ','がいさ'],c:0,exp:'会社 = かいしゃ (company)'},
{id:'k033',type:'kanji',category:'漢字',difficulty:'hard',
 s:'病院で先生に薬をもらいました。',a:'「薬」の読み方は？',
 o:['くすり','やすり','くすく','やくそく'],c:0,exp:'薬 = くすり (medicine)'},
{id:'k034',type:'kanji',category:'漢字',difficulty:'medium',
 s:'この映画はとても有名です。',a:'「有名」の読み方は？',
 o:['ゆうめい','ゆめい','ゆうみょう','ゆみょう'],c:0,exp:'有名 = ゆうめい (famous)'},
{id:'k035',type:'kanji',category:'漢字',difficulty:'hard',
 s:'駅の近くに便利なコンビニがあります。',a:'「便利」の読み方は？',
 o:['べんり','びんり','ふんり','ぷんり'],c:0,exp:'便利 = べんり (convenient)'},

// ── VOCABULARY ────────────────────────────────────────────
{id:'v001',type:'vocab',category:'語彙',difficulty:'easy',
 s:'日本では、はる·なつ·あき·ふゆの四つの ＿＿ があります。',a:'正しい言葉を選んでください。',
 o:['てんき','きぶん','きおん','きせつ'],c:3,exp:'きせつ (季節) = seasons',gp:'weather/nature'},
{id:'v002',type:'vocab',category:'語彙',difficulty:'easy',
 s:'きのうならったことをもう ＿＿ しまいました。',a:'正しい言葉を選んでください。',
 o:['わすれて','すてて','なくして','とって'],c:0,exp:'わすれてしまいました — accidentally forgot',gp:'〜てしまう'},
{id:'v003',type:'vocab',category:'語彙',difficulty:'medium',
 s:'シャツのうりばは３がいです。あの ＿＿ でいってください。',a:'正しい言葉を選んでください。',
 o:['ドア','タクシー','サンダル','エスカレーター'],c:3,exp:'エスカレーター = escalator',gp:'katakana'},
{id:'v004',type:'vocab',category:'語彙',difficulty:'easy',
 s:'あまり勉強しなかったので、テストのてんが ＿＿ です。',a:'正しい言葉を選んでください。',
 o:['しんぱい','きけん','あんぜん','あんしん'],c:0,exp:'しんぱい (心配) = worried',gp:'adjectives'},
{id:'v005',type:'vocab',category:'語彙',difficulty:'medium',
 s:'おもしろいえいがだと聞いたので、＿＿ みたいです。',a:'正しい言葉を選んでください。',
 o:['たぶん','そんなに','ぜひ','きゅうに'],c:2,exp:'ぜひ = by all means, definitely',gp:'adverbs'},
{id:'v006',type:'vocab',category:'語彙',difficulty:'easy',
 s:'たかださんは ＿＿ をしながらだいがくにかよっています。',a:'正しい言葉を選んでください。',
 o:['オートバイ','デパート','アルバイト','カレンダー'],c:2,exp:'アルバイト = part-time job',gp:'katakana'},
{id:'v007',type:'vocab',category:'語彙',difficulty:'medium',
 s:'はなこさんは白いスカートと ＿＿ をはいています。',a:'正しい言葉を選んでください。',
 o:['セーター','ハンカチ','サンダル','オーバー'],c:2,exp:'サンダル = sandals (はく = wear on feet/legs)',gp:'clothing'},
{id:'v008',type:'vocab',category:'語彙',difficulty:'easy',
 s:'父はとうきょうへ行くと、いつも ＿＿ をかってきてくれます。',a:'正しい言葉を選んでください。',
 o:['おまつり','おれい','おみやげ','おいわい'],c:2,exp:'おみやげ (お土産) = souvenir/gift from trip',gp:'gift-giving'},
{id:'v009',type:'vocab',category:'語彙',difficulty:'easy',
 s:'あのあたらしい ＿＿ はデパートです。',a:'正しい言葉を選んでください。',
 o:['アパート','ホテル','プール','ビル'],c:3,exp:'ビル = building',gp:'katakana'},
{id:'v010',type:'vocab',category:'語彙',difficulty:'easy',
 s:'じゅぎょうがおわってから、まいにち、ピンポンの ＿＿ をします。',a:'正しい言葉を選んでください。',
 o:['しゅみ','うんどう','れんしゅう','しゅうかん'],c:2,exp:'れんしゅう (練習) = practice',gp:'activities'},
{id:'v011',type:'vocab',category:'語彙',difficulty:'medium',
 s:'かぜをひいたので、病院へ行って ＿＿ をもらいました。',a:'正しい言葉を選んでください。',
 o:['くすり','ごちそう','おみやげ','プレゼント'],c:0,exp:'くすり (薬) = medicine',gp:'health'},
{id:'v012',type:'vocab',category:'語彙',difficulty:'medium',
 s:'この問題はむずかしくて、＿＿ わかりません。',a:'正しい言葉を選んでください。',
 o:['ときどき','ぜんぜん','たぶん','もうすぐ'],c:1,exp:'ぜんぜん〜ない = not at all',gp:'adverbs'},
{id:'v013',type:'vocab',category:'語彙',difficulty:'medium',
 s:'山田さんは毎日 ＿＿ で会社に行っています。',a:'正しい言葉を選んでください。',
 o:['ちかてつ','デパート','アパート','レストラン'],c:0,exp:'ちかてつ (地下鉄) = subway',gp:'transport'},
{id:'v014',type:'vocab',category:'語彙',difficulty:'hard',
 s:'このコンサートのチケットは ＿＿ なので、はやく買ってください。',a:'正しい言葉を選んでください。',
 o:['しずか','にぎやか','にんき','きれい'],c:2,exp:'にんき (人気) = popular',gp:'adjectives'},
{id:'v015',type:'vocab',category:'語彙',difficulty:'hard',
 s:'旅行の前に、ホテルを ＿＿ おきました。',a:'正しい言葉を選んでください。',
 o:['よやくして','けんかして','しんぱいして','れんしゅうして'],c:0,exp:'よやく (予約) = reservation, booking',gp:'〜ておく'},
{id:'v016',type:'vocab',category:'語彙',difficulty:'medium',
 s:'電車の中でおさないでください。とても ＿＿ です。',a:'正しい言葉を選んでください。',
 o:['あぶない','たのしい','すずしい','やさしい'],c:0,exp:'あぶない (危ない) = dangerous',gp:'adjectives'},
{id:'v017',type:'vocab',category:'語彙',difficulty:'medium',
 s:'子どもに ＿＿ をかってやりました。とてもよろこびました。',a:'正しい言葉を選んでください。',
 o:['にんぎょう','おみやげ','くすり','でんしゃ'],c:0,exp:'にんぎょう (人形) = doll',gp:'〜てやる'},
{id:'v018',type:'vocab',category:'語彙',difficulty:'hard',
 s:'来週の会議に ＿＿ かどうか、まだわかりません。',a:'正しい言葉を選んでください。',
 o:['でられる','でられない','でる','でた'],c:0,exp:'でられる = potential form of 出る (can attend)',gp:'potential form'},
{id:'v019',type:'vocab',category:'語彙',difficulty:'easy',
 s:'すみません、この漢字の ＿＿ を教えてください。',a:'正しい言葉を選んでください。',
 o:['いみ','はなし','ことば','かいわ'],c:0,exp:'いみ (意味) = meaning',gp:'study'},
{id:'v020',type:'vocab',category:'語彙',difficulty:'medium',
 s:'もうすこし ＿＿ はなしてください。よく聞こえません。',a:'正しい言葉を選んでください。',
 o:['おおきく','おおきい','おおきくて','おおきな'],c:0,exp:'おおきく + verb = adverb form of 大きい',gp:'adverb form'},

// ── GRAMMAR ───────────────────────────────────────────────
{id:'g001',type:'grammar',category:'文法',difficulty:'easy',gp:'〜てあげる',
 s:'友達が重い荷物を持っていたので、＿＿。',a:'正しい文を選んでください。',
 o:['もってあげました','もってもらいました','もってくれました','もっていました'],c:0,
 exp:'〜てあげる = I do something for someone else (you are the giver)'},
{id:'g002',type:'grammar',category:'文法',difficulty:'easy',gp:'〜てくれる',
 s:'先生がわからない問題を説明＿＿。',a:'正しい形を選んでください。',
 o:['してあげました','してもらいました','してくれました','しました'],c:2,
 exp:'〜てくれる = someone does something for me/my in-group (the giver is the subject)'},
{id:'g003',type:'grammar',category:'文法',difficulty:'easy',gp:'〜てもらう',
 s:'私は弟に宿題を手伝って＿＿。',a:'正しい形を選んでください。',
 o:['あげました','くれました','もらいました','やりました'],c:2,
 exp:'〜てもらう = I receive the benefit of someone\'s action'},
{id:'g004',type:'grammar',category:'文法',difficulty:'medium',gp:'〜てあげる/くれる/もらう',
 s:'母は毎朝おべんとうを作って＿＿。（私のために）',a:'正しい形を選んでください。',
 o:['あげます','もらいます','くれます','やります'],c:2,
 exp:'Mother is doing something for ME → くれます'},
{id:'g005',type:'grammar',category:'文法',difficulty:'medium',gp:'〜てしまう',
 s:'大切なメールをまちがえて消して＿＿。',a:'正しい形を選んでください。',
 o:['みました','おきました','しまいました','あげました'],c:2,
 exp:'〜てしまう = accidentally did something / regret'},
{id:'g006',type:'grammar',category:'文法',difficulty:'easy',gp:'〜てしまう',
 s:'財布を家に忘れて＿＿ので、何も買えませんでした。',a:'正しい形を選んでください。',
 o:['しまった','みた','おいた','くれた'],c:0,
 exp:'〜てしまった = I (unfortunately) left it behind'},
{id:'g007',type:'grammar',category:'文法',difficulty:'medium',gp:'〜ておく',
 s:'パーティーの前に食べ物を買って＿＿ました。',a:'正しい形を選んでください。',
 o:['み','あげ','おき','しまい'],c:2,
 exp:'〜ておく = to do something in advance, in preparation'},
{id:'g008',type:'grammar',category:'文法',difficulty:'medium',gp:'〜ておく',
 s:'旅行のまえに地図を調べて＿＿ほうがいいですよ。',a:'正しい形を選んでください。',
 o:['みた','おいた','しまった','くれた'],c:1,
 exp:'〜ておく = prepare beforehand'},
{id:'g009',type:'grammar',category:'文法',difficulty:'easy',gp:'〜てみる',
 s:'このお菓子、おいしそうですね。一つ食べて＿＿ください。',a:'正しい形を選んでください。',
 o:['あげて','くれて','みて','しまって'],c:2,
 exp:'〜てみる = to try doing something'},
{id:'g010',type:'grammar',category:'文法',difficulty:'medium',gp:'〜てみる',
 s:'日本語の歌を歌って＿＿たら、とても楽しかったです。',a:'正しい形を選んでください。',
 o:['おい','み','あげ','くれ'],c:1,
 exp:'〜てみる = tried doing it and found it enjoyable'},
{id:'g011',type:'grammar',category:'文法',difficulty:'medium',gp:'〜ているところ',
 s:'今、ちょうどごはんを食べて＿＿です。あとで電話します。',a:'正しい形を選んでください。',
 o:['いたところ','いるところ','おくところ','みるところ'],c:1,
 exp:'〜ているところ = in the middle of doing (right now)'},
{id:'g012',type:'grammar',category:'文法',difficulty:'hard',gp:'〜ているところ',
 s:'先生が教室に入ってきたとき、学生は話して＿＿。',a:'正しい形を選んでください。',
 o:['いたところでした','いたことでした','おいたところでした','みたところでした'],c:0,
 exp:'〜ていたところ = was in the middle of doing (past)'},
{id:'g013',type:'grammar',category:'文法',difficulty:'medium',gp:'〜たばかり',
 s:'さっき昼ごはんを食べた＿＿なので、おなかがいっぱいです。',a:'正しい形を選んでください。',
 o:['ところ','ばかり','まま','つもり'],c:1,
 exp:'〜たばかり = just did something (very recently)'},
{id:'g014',type:'grammar',category:'文法',difficulty:'easy',gp:'〜たばかり',
 s:'この会社に入社した＿＿で、まだ何もわかりません。',a:'正しい形を選んでください。',
 o:['ところ','ばかり','まま','みたい'],c:1,
 exp:'〜たばかり = just joined, very new'},
{id:'g015',type:'grammar',category:'文法',difficulty:'hard',gp:'〜まま',
 s:'テレビをつけた＿＿寝てしまいました。',a:'正しい形を選んでください。',
 o:['ところ','ばかり','まま','つもり'],c:2,
 exp:'〜まま = left in that state (TV still on while sleeping)'},
{id:'g016',type:'grammar',category:'文法',difficulty:'hard',gp:'〜まま',
 s:'くつをはいた＿＿部屋に入らないでください。',a:'正しい形を選んでください。',
 o:['ところ','ばかり','まま','みたい'],c:2,
 exp:'〜まま = without changing state (shoes still on)'},
{id:'g017',type:'grammar',category:'文法',difficulty:'medium',gp:'potential form',
 s:'もっと速く＿＿ように、毎日練習しています。',a:'正しい形を選んでください。',
 o:['はしる','はしれる','はしった','はしっている'],c:1,
 exp:'〜ように + potential = practice so that I can do something'},
{id:'g018',type:'grammar',category:'文法',difficulty:'medium',gp:'potential form',
 s:'子どもの時は、ピアノが＿＿ませんでした。',a:'正しい形を選んでください。',
 o:['ひかれ','ひき','ひけ','ひける'],c:2,
 exp:'弾ける → 弾けません = could not play (potential negative)'},
{id:'g019',type:'grammar',category:'文法',difficulty:'easy',gp:'〜ながら',
 s:'音楽を聴き＿＿勉強するのは好きじゃないです。',a:'正しい形を選んでください。',
 o:['ながら','まま','ところ','ばかり'],c:0,
 exp:'〜ながら = while doing X, do Y simultaneously'},
{id:'g020',type:'grammar',category:'文法',difficulty:'hard',gp:'〜てあげる/くれる/もらう',
 s:'田中さんに空港まで送って＿＿ので、とても助かりました。',a:'正しい形を選んでください。',
 o:['あげた','くれた','もらった','やった'],c:1,
 exp:'Tanaka-san did something FOR ME → くれた'},

// ── CHALLENGE QUESTIONS (apply grammar in new situations) ──
{id:'c001',type:'grammar',category:'文法',difficulty:'challenge',gp:'〜てしまう',
 s:'新しいスマホを買ったばかりなのに、もう壊して＿＿。どうしよう…',a:'正しい形を選んでください。',
 o:['みました','おきました','しまいました','もらいました'],c:2,
 exp:'〜てしまいました = expresses strong regret about breaking something'},
{id:'c002',type:'grammar',category:'文法',difficulty:'challenge',gp:'〜てくれる vs 〜てもらう',
 s:'どちらが正しいですか？「先生は私に漢字を教えて＿＿。」',a:'正しい形を選んでください。',
 o:['あげました','くれました','もらいました','やりました'],c:1,
 exp:'先生 → 私: teacher gives benefit to me = くれました'},
{id:'c003',type:'grammar',category:'文法',difficulty:'challenge',gp:'〜ておく',
 s:'明日プレゼンがあるので、今日スライドを準備して＿＿ました。',a:'正しい形を選んでください。',
 o:['み','あげ','おき','しまい'],c:2,
 exp:'〜ておく = did it in advance to be ready for tomorrow'},
{id:'c004',type:'grammar',category:'文法',difficulty:'challenge',gp:'〜たばかり vs 〜ているところ',
 s:'「今何をしていますか？」「ちょうど宿題を終わらせた＿＿です。」',a:'正しい形を選んでください。',
 o:['まま','ばかり','ところ','ながら'],c:1,
 exp:'〜たばかり = just finished (moments ago)'},
];

// Remove duplicates by id
const seen = new Set();
const QUESTIONS = QUESTION_BANK.filter(q => {
  if (seen.has(q.id)) return false;
  seen.add(q.id);
  return true;
});

// Shuffle an array (Fisher-Yates)
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Return a question with shuffled options (correct answer tracked by value, not index)
function shuffledQuestion(q) {
  const correctValue = q.o[q.c];
  const shuffledOpts = shuffle(q.o);
  return {
    ...q,
    o: shuffledOpts,
    c: shuffledOpts.indexOf(correctValue)
  };
}

// Get a random set of questions for a test mode
function getTestQuestions(mode) {
  const kanji = shuffle(QUESTIONS.filter(q => q.type === 'kanji'));
  const vocab = shuffle(QUESTIONS.filter(q => q.type === 'vocab'));
  const grammar = shuffle(QUESTIONS.filter(q => q.type === 'grammar'));
  const challenge = shuffle(QUESTIONS.filter(q => q.difficulty === 'challenge'));

  let pool = [];
  if (mode === 'quick') {
    pool = [...kanji.slice(0,7), ...vocab.slice(0,7), ...grammar.slice(0,6)];
  } else if (mode === 'full') {
    pool = [...kanji.slice(0,12), ...vocab.slice(0,12), ...grammar.slice(0,12), ...challenge.slice(0,4)];
  } else { // mock
    pool = [...kanji.slice(0,15), ...vocab.slice(0,15), ...grammar.slice(0,18), ...challenge.slice(0,4)];
  }
  return shuffle(pool).map(shuffledQuestion);
}

const SPEAKING_Q = [
  {tag:'〜てあげる/くれる',q:'ご家族やともだちに最近何かしてあげましたか？',hint:'友達に日本語を教えてあげました。/ 夫にコーヒーを作ってあげました。'},
  {tag:'〜てもらう',q:'最近、だれかに何かしてもらいましたか？',hint:'夫にごはんを作ってもらいました。/ 友達に道を教えてもらいました。'},
  {tag:'〜てしまう',q:'最近、困ったこと、うっかりしたことを話してください。',hint:'財布を忘れてしまいました。/ 宿題をなくしてしまいました。'},
  {tag:'〜たばかり',q:'最近始めたこと、または終わったことは何ですか？',hint:'日本語のレッスンを始めたばかりです。/ ごはんを食べたばかりです。'},
  {tag:'〜ているところ',q:'今日の午後、何をしているところでしたか？',hint:'勉強しているところでした。/ テレビを見ているところでした。'},
  {tag:'〜ておく',q:'旅行の前に何を準備しておきますか？',hint:'ホテルを予約しておきます。/ パスポートを確認しておきます。'},
  {tag:'〜てみる',q:'食べてみたい、行ってみたい、やってみたいことは何ですか？',hint:'北海道に行ってみたいです。/ 新しい料理を作ってみたいです。'},
  {tag:'〜まま',q:'最近、何かそのままにしておいたことはありますか？',hint:'窓を開けたまま寝てしまいました。/ テレビをつけたまま出かけました。'},
  {tag:'potential form',q:'日本語の勉強で、何ができるようになりましたか？',hint:'ひらがなが読めるようになりました。/ 少し話せるようになりました。'},
  {tag:'季節・天気の語彙',q:'好きな季節はいつですか？その理由を教えてください。',hint:'Use: 風、海、山、暑い、涼しい、きせつ、たのしい'},
  {tag:'フリートーク',q:'みんなの日本語の中で一番むずかしかった文法は何ですか？',hint:'Use grammar patterns you\'ve studied. Give an example sentence.'},
];
