const UPSTASH_URL = process.env.KV_REST_API_URL;
const UPSTASH_TOKEN = process.env.KV_REST_API_TOKEN;

async function redisSet(key, value) {
  const res = await fetch(`${UPSTASH_URL}`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${UPSTASH_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(['SET', key, JSON.stringify(value)]),
  });
  const data = await res.json();
  if (data.error) throw new Error(data.error);
  return data.result;
}

const QUESTIONS = [
  // ── KANJI ──────────────────────────────────────────────
  {id:'k001',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'自分で旅行を計画するのは楽しいです。',a:'「自分」の読み方は？',
   o:['じぶん','ちっぷん','じっぷん','ちぶん'],c:0,exp:'自分 = じぶん (oneself)'},
  {id:'k002',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'自分で旅行を計画するのは楽しいです。',a:'「旅行」の読み方は？',
   o:['りゅうこ','りょうこ','りょこう','りゅこう'],c:2,exp:'旅行 = りょこう (travel)'},
  {id:'k003',type:'kanji',category:'漢字',difficulty:'medium',lesson:26,gp:'kanji-reading',
   s:'自分で旅行を計画するのは楽しいです。',a:'「計画」の読み方は？',
   o:['けいかく','けいが','げいかく','けが'],c:0,exp:'計画 = けいかく (plan/schedule)'},
  {id:'k004',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'自分で旅行を計画するのは楽しいです。',a:'「楽しい」の読み方は？',
   o:['うれしい','うつくしい','たのしい','いそがしい'],c:2,exp:'楽しい = たのしい (fun, enjoyable)'},
  {id:'k005',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-reading',
   s:'この学生は毎日地下鉄で大学に通っています。',a:'「地下鉄」の読み方は？',
   o:['じげてつ','じがてつ','ちげてつ','ちかてつ'],c:3,exp:'地下鉄 = ちかてつ (subway)'},
  {id:'k006',type:'kanji',category:'漢字',difficulty:'easy',lesson:27,gp:'kanji-reading',
   s:'この学生は毎日地下鉄で大学に通っています。',a:'「大学」の読み方は？',
   o:['たいがく','だいかく','たいかく','だいがく'],c:3,exp:'大学 = だいがく (university)'},
  {id:'k007',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-reading',
   s:'この学生は毎日地下鉄で大学に通っています。',a:'「通って」の読み方は？',
   o:['かえって','かよって','かおって','いって'],c:1,exp:'通う = かよう (to commute)'},
  {id:'k008',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'姉がいつも食事の用意をしてくれます。',a:'「姉」の読み方は？',
   o:['いもうと','おとうと','あね','あに'],c:2,exp:'姉 = あね (older sister)'},
  {id:'k009',type:'kanji',category:'漢字',difficulty:'medium',lesson:26,gp:'kanji-reading',
   s:'姉がいつも食事の用意をしてくれます。',a:'「食事」の読み方は？',
   o:['しょくじ','しょうじ','そうじ','そくじ'],c:0,exp:'食事 = しょくじ (meal)'},
  {id:'k010',type:'kanji',category:'漢字',difficulty:'medium',lesson:26,gp:'kanji-reading',
   s:'姉がいつも食事の用意をしてくれます。',a:'「用意」の読み方は？',
   o:['よい','ようい','よじ','ようじ'],c:1,exp:'用意 = ようい (preparation)'},
  {id:'k011',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-writing',
   s:'彼女はこうちょくしたようにうごかない。',a:'「うごかない」の漢字は？',
   o:['動かない','働かない','重かない','衝かない'],c:0,exp:'動く = うごく (to move)'},
  {id:'k012',type:'kanji',category:'漢字',difficulty:'hard',lesson:28,gp:'kanji-reading',
   s:'奈良と京都は日本の古い都です。',a:'「都」の読み方は？',
   o:['みなと','ふるさと','みやこ','いなか'],c:2,exp:'都 = みやこ (capital city)'},
  {id:'k013',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'趣味としてじゅうどうを習うつもりです。',a:'「趣味」の読み方は？',
   o:['しゅみ','きょうみ','ちゅみ','ちょうみ'],c:0,exp:'趣味 = しゅみ (hobby)'},
  {id:'k014',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-writing',
   s:'きゅうに空が暗くなりました。',a:'「きゅうに」の漢字は？',
   o:['早に','速に','突に','急に'],c:3,exp:'急に = きゅうに (suddenly)'},
  {id:'k015',type:'kanji',category:'漢字',difficulty:'hard',lesson:28,gp:'kanji-reading',
   s:'兄が入院したので、花を持ってお見舞いに行った。',a:'「お見舞い」の読み方は？',
   o:['おみあい','おみまい','おけんまい','おけんあい'],c:1,exp:'お見舞い = おみまい (hospital visit)'},
  {id:'k016',type:'kanji',category:'漢字',difficulty:'hard',lesson:28,gp:'kanji-writing',
   s:'のどがかわいています。水が飲みたいです。',a:'「かわいて」の漢字は？',
   o:['乾いて','変いて','掛いて','渇いて'],c:3,exp:'渇く = かわく (to be thirsty) ≠ 乾く (to dry out)'},
  {id:'k017',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'先生の奥さんはとても優しいです。',a:'「優しい」の読み方は？',
   o:['きびしい','やさしい','たのしい','したしい'],c:1,exp:'優しい = やさしい (kind, gentle)'},
  {id:'k018',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-reading',
   s:'ディズニーランドで姉に人形を買ってやった。',a:'「人形」の読み方は？',
   o:['にんけい','じんけい','にんぎょう','じんぎょう'],c:2,exp:'人形 = にんぎょう (doll)'},
  {id:'k019',type:'kanji',category:'漢字',difficulty:'hard',lesson:28,gp:'kanji-reading',
   s:'おばあさんが昔のいろんな物語を話してくれた。',a:'「物語」の読み方は？',
   o:['ものはなし','ものばなし','ものかたり','ものがたり'],c:3,exp:'物語 = ものがたり (story, tale)'},
  {id:'k020',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-writing',
   s:'友達がいなくて、さびしいです。',a:'「さびしい」の漢字は？',
   o:['悲しい','厳しい','美しい','寂しい'],c:3,exp:'寂しい = さびしい (lonely)'},
  {id:'k021',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'海から強い風がふいてきた。',a:'「海」の読み方は？',
   o:['うみ','あめ','かぜ','うた'],c:0,exp:'海 = うみ (sea, ocean)'},
  {id:'k022',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'海から強い風がふいてきた。',a:'「強い」の読み方は？',
   o:['おもい','あまい','すごい','つよい'],c:3,exp:'強い = つよい (strong)'},
  {id:'k023',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'海から強い風がふいてきた。',a:'「風」の読み方は？',
   o:['かべ','かばん','かぜ','かぎ'],c:2,exp:'風 = かぜ (wind)'},
  {id:'k024',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「魚」の読み方は？',
   o:['こめ','さかな','にく','やさい'],c:1,exp:'魚 = さかな (fish)'},
  {id:'k025',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-reading',
   s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「夕飯」の読み方は？',
   o:['ちゅうはん','ゆうはん','ちゅうしょく','ゆうしょく'],c:1,exp:'夕飯 = ゆうはん (dinner)'},
  {id:'k026',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「使った」の読み方は？',
   o:['つかった','つくった','はって','きった'],c:0,exp:'使う = つかう (to use)'},
  {id:'k027',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'川で魚をとりました。今日の夕飯はその魚を使った料理にします。',a:'「料理」の読み方は？',
   o:['りょり','りょいり','りょうり','りょおい'],c:2,exp:'料理 = りょうり (cooking, dish)'},
  {id:'k028',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-reading',
   s:'となりの教室から歌が聞こえるので、まどを閉めてください。',a:'「教室」の読み方は？',
   o:['きょうじつ','きゅうしつ','きゅうじつ','きょうしつ'],c:3,exp:'教室 = きょうしつ (classroom)'},
  {id:'k029',type:'kanji',category:'漢字',difficulty:'easy',lesson:26,gp:'kanji-reading',
   s:'となりの教室から歌が聞こえるので、まどを閉めてください。',a:'「歌」の読み方は？',
   o:['うた','おた','きえ','こえ'],c:0,exp:'歌 = うた (song)'},
  {id:'k030',type:'kanji',category:'漢字',difficulty:'medium',lesson:27,gp:'kanji-reading',
   s:'となりの教室から歌が聞こえるので、まどを閉めてください。',a:'「閉めて」の読み方は？',
   o:['あめて','とめて','しめて','やめて'],c:2,exp:'閉める = しめる (to close)'},

  // ── VOCABULARY ─────────────────────────────────────────
  {id:'v001',type:'vocab',category:'語彙',difficulty:'easy',lesson:26,gp:'seasons',
   s:'日本では、はる·なつ·あき·ふゆの四つの＿＿があります。',a:'正しい言葉を選んでください。',
   o:['てんき','きぶん','きおん','きせつ'],c:3,exp:'きせつ (季節) = seasons'},
  {id:'v002',type:'vocab',category:'語彙',difficulty:'easy',lesson:26,gp:'〜てしまう',
   s:'きのうならったことをもう＿＿しまいました。',a:'正しい言葉を選んでください。',
   o:['わすれて','すてて','なくして','とって'],c:0,exp:'わすれてしまいました = accidentally forgot'},
  {id:'v003',type:'vocab',category:'語彙',difficulty:'medium',lesson:27,gp:'katakana',
   s:'シャツのうりばは３がいです。あの＿＿でいってください。',a:'正しい言葉を選んでください。',
   o:['ドア','タクシー','サンダル','エスカレーター'],c:3,exp:'エスカレーター = escalator'},
  {id:'v004',type:'vocab',category:'語彙',difficulty:'easy',lesson:26,gp:'adjectives',
   s:'あまり勉強しなかったので、テストのてんが＿＿です。',a:'正しい言葉を選んでください。',
   o:['しんぱい','きけん','あんぜん','あんしん'],c:0,exp:'しんぱい (心配) = worried'},
  {id:'v005',type:'vocab',category:'語彙',difficulty:'medium',lesson:27,gp:'adverbs',
   s:'おもしろいえいがだと聞いたので、＿＿みたいです。',a:'正しい言葉を選んでください。',
   o:['たぶん','そんなに','ぜひ','きゅうに'],c:2,exp:'ぜひ = by all means, definitely'},
  {id:'v006',type:'vocab',category:'語彙',difficulty:'easy',lesson:26,gp:'katakana',
   s:'たかださんは＿＿をしながらだいがくにかよっています。',a:'正しい言葉を選んでください。',
   o:['オートバイ','デパート','アルバイト','カレンダー'],c:2,exp:'アルバイト = part-time job'},
  {id:'v007',type:'vocab',category:'語彙',difficulty:'medium',lesson:27,gp:'clothing',
   s:'はなこさんは白いスカートと＿＿をはいています。',a:'正しい言葉を選んでください。',
   o:['セーター','ハンカチ','サンダル','オーバー'],c:2,exp:'サンダル = sandals (はく = wear on feet)'},
  {id:'v008',type:'vocab',category:'語彙',difficulty:'easy',lesson:26,gp:'gift-giving',
   s:'父はとうきょうへ行くと、いつも＿＿をかってきてくれます。',a:'正しい言葉を選んでください。',
   o:['おまつり','おれい','おみやげ','おいわい'],c:2,exp:'おみやげ (お土産) = souvenir/gift from trip'},
  {id:'v009',type:'vocab',category:'語彙',difficulty:'easy',lesson:26,gp:'katakana',
   s:'あのあたらしい＿＿はデパートです。',a:'正しい言葉を選んでください。',
   o:['アパート','ホテル','プール','ビル'],c:3,exp:'ビル = building'},
  {id:'v010',type:'vocab',category:'語彙',difficulty:'easy',lesson:26,gp:'activities',
   s:'じゅぎょうがおわってから、まいにち、ピンポンの＿＿をします。',a:'正しい言葉を選んでください。',
   o:['しゅみ','うんどう','れんしゅう','しゅうかん'],c:2,exp:'れんしゅう (練習) = practice'},

  // ── GRAMMAR ────────────────────────────────────────────
  {id:'g001',type:'grammar',category:'文法',difficulty:'easy',lesson:26,gp:'〜てあげる',
   s:'友達が重い荷物を持っていたので＿＿。',a:'正しい形を選んでください。',
   o:['もってあげました','もってもらいました','もってくれました','もっていました'],c:0,
   exp:'〜てあげる = I do something for someone else'},
  {id:'g002',type:'grammar',category:'文法',difficulty:'easy',lesson:26,gp:'〜てくれる',
   s:'先生がわからない問題を説明＿＿。',a:'正しい形を選んでください。',
   o:['してあげました','してもらいました','してくれました','しました'],c:2,
   exp:'〜てくれる = someone does something for me'},
  {id:'g003',type:'grammar',category:'文法',difficulty:'easy',lesson:26,gp:'〜てもらう',
   s:'私は弟に宿題を手伝って＿＿。',a:'正しい形を選んでください。',
   o:['あげました','くれました','もらいました','やりました'],c:2,
   exp:'〜てもらう = I receive the benefit of someone\'s action'},
  {id:'g004',type:'grammar',category:'文法',difficulty:'medium',lesson:26,gp:'〜てあげる/くれる/もらう',
   s:'母は毎朝おべんとうを作って＿＿。（私のために）',a:'正しい形を選んでください。',
   o:['あげます','もらいます','くれます','やります'],c:2,
   exp:'Mother → me: teacher gives benefit to me = くれます'},
  {id:'g005',type:'grammar',category:'文法',difficulty:'easy',lesson:27,gp:'〜てしまう',
   s:'大切なメールをまちがえて消して＿＿。',a:'正しい形を選んでください。',
   o:['みました','おきました','しまいました','あげました'],c:2,
   exp:'〜てしまう = accidentally did / regret'},
  {id:'g006',type:'grammar',category:'文法',difficulty:'easy',lesson:27,gp:'〜てしまう',
   s:'財布を家に忘れて＿＿ので、何も買えませんでした。',a:'正しい形を選んでください。',
   o:['しまった','みた','おいた','くれた'],c:0,
   exp:'〜てしまった = I (unfortunately) left it behind'},
  {id:'g007',type:'grammar',category:'文法',difficulty:'medium',lesson:28,gp:'〜ておく',
   s:'パーティーの前に食べ物を買って＿＿ました。',a:'正しい形を選んでください。',
   o:['み','あげ','おき','しまい'],c:2,
   exp:'〜ておく = to do something in advance'},
  {id:'g008',type:'grammar',category:'文法',difficulty:'medium',lesson:28,gp:'〜ておく',
   s:'旅行のまえに地図を調べて＿＿ほうがいいですよ。',a:'正しい形を選んでください。',
   o:['みた','おいた','しまった','くれた'],c:1,
   exp:'〜ておく = prepare beforehand'},
  {id:'g009',type:'grammar',category:'文法',difficulty:'easy',lesson:27,gp:'〜てみる',
   s:'このお菓子、おいしそうですね。一つ食べて＿＿ください。',a:'正しい形を選んでください。',
   o:['あげて','くれて','みて','しまって'],c:2,
   exp:'〜てみる = to try doing something'},
  {id:'g010',type:'grammar',category:'文法',difficulty:'medium',lesson:28,gp:'〜ているところ',
   s:'今、ちょうどごはんを食べて＿＿です。あとで電話します。',a:'正しい形を選んでください。',
   o:['いたところ','いるところ','おくところ','みるところ'],c:1,
   exp:'〜ているところ = in the middle of doing (right now)'},
  {id:'g011',type:'grammar',category:'文法',difficulty:'medium',lesson:28,gp:'〜たばかり',
   s:'さっき昼ごはんを食べた＿＿なので、おなかがいっぱいです。',a:'正しい形を選んでください。',
   o:['ところ','ばかり','まま','つもり'],c:1,
   exp:'〜たばかり = just did something (very recently)'},
  {id:'g012',type:'grammar',category:'文法',difficulty:'hard',lesson:28,gp:'〜まま',
   s:'テレビをつけた＿＿寝てしまいました。',a:'正しい形を選んでください。',
   o:['ところ','ばかり','まま','つもり'],c:2,
   exp:'〜まま = left in that state (TV still on while sleeping)'},
  {id:'g013',type:'grammar',category:'文法',difficulty:'medium',lesson:27,gp:'potential form',
   s:'もっと速く＿＿ように、毎日練習しています。',a:'正しい形を選んでください。',
   o:['はしる','はしれる','はしった','はしっている'],c:1,
   exp:'〜ように + potential = practice so I can do something'},
  {id:'g014',type:'grammar',category:'文法',difficulty:'easy',lesson:26,gp:'〜ながら',
   s:'音楽を聴き＿＿勉強するのは好きじゃないです。',a:'正しい形を選んでください。',
   o:['ながら','まま','ところ','ばかり'],c:0,
   exp:'〜ながら = while doing X, do Y simultaneously'},
  {id:'g015',type:'grammar',category:'文法',difficulty:'challenge',lesson:28,gp:'〜てしまう',
   s:'新しいスマホを買ったばかりなのに、もう壊して＿＿。どうしよう…',a:'正しい形を選んでください。',
   o:['みました','おきました','しまいました','もらいました'],c:2,
   exp:'〜てしまいました = strong regret about breaking something'},
  {id:'g016',type:'grammar',category:'文法',difficulty:'challenge',lesson:26,gp:'〜てくれる vs 〜てもらう',
   s:'先生は私に漢字を教えて＿＿。（先生が私に）',a:'正しい形を選んでください。',
   o:['あげました','くれました','もらいました','やりました'],c:1,
   exp:'先生 → 私: teacher gives benefit to me = くれました'},
  {id:'g017',type:'grammar',category:'文法',difficulty:'challenge',lesson:28,gp:'〜ておく',
   s:'明日プレゼンがあるので、今日スライドを準備して＿＿ました。',a:'正しい形を選んでください。',
   o:['み','あげ','おき','しまい'],c:2,
   exp:'〜ておく = did it in advance to be ready for tomorrow'},
  {id:'g018',type:'grammar',category:'文法',difficulty:'challenge',lesson:28,gp:'〜たばかり vs 〜ているところ',
   s:'「今何をしていますか？」「ちょうど宿題を終わらせた＿＿です。」',a:'正しい形を選んでください。',
   o:['まま','ばかり','ところ','ながら'],c:1,
   exp:'〜たばかり = just finished (moments ago)'},
];

const FLASHCARDS = [
  {id:'f001',lesson:26,type:'vocab',front:'旅行',reading:'りょこう',meaning:'travel, trip',
   example:'来年、日本へ旅行に行きたいです。',exampleReading:'らいねん、にほんへりょこうにいきたいです。',
   exampleMeaning:'I want to travel to Japan next year.'},
  {id:'f002',lesson:26,type:'vocab',front:'計画',reading:'けいかく',meaning:'plan, schedule',
   example:'旅行の計画を立てました。',exampleReading:'りょこうのけいかくをたてました。',
   exampleMeaning:'I made a plan for the trip.'},
  {id:'f003',lesson:27,type:'vocab',front:'地下鉄',reading:'ちかてつ',meaning:'subway, underground train',
   example:'毎日地下鉄で会社に行きます。',exampleReading:'まいにちちかてつでかいしゃにいきます。',
   exampleMeaning:'I go to work by subway every day.'},
  {id:'f004',lesson:27,type:'vocab',front:'大学',reading:'だいがく',meaning:'university, college',
   example:'姉は大学で日本語を勉強しています。',exampleReading:'あねはだいがくでにほんごをべんきょうしています。',
   exampleMeaning:'My older sister is studying Japanese at university.'},
  {id:'f005',lesson:26,type:'vocab',front:'食事',reading:'しょくじ',meaning:'meal, dining',
   example:'家族と一緒に食事をするのが好きです。',exampleReading:'かぞくといっしょにしょくじをするのがすきです。',
   exampleMeaning:'I like dining together with my family.'},
  {id:'f006',lesson:26,type:'vocab',front:'用意',reading:'ようい',meaning:'preparation, getting ready',
   example:'パーティーの用意ができました。',exampleReading:'パーティーのよういができました。',
   exampleMeaning:'The preparations for the party are done.'},
  {id:'f007',lesson:26,type:'vocab',front:'趣味',reading:'しゅみ',meaning:'hobby, interest',
   example:'私の趣味は料理を作ることです。',exampleReading:'わたしのしゅみはりょうりをつくることです。',
   exampleMeaning:'My hobby is cooking.'},
  {id:'f008',lesson:28,type:'vocab',front:'物語',reading:'ものがたり',meaning:'story, tale',
   example:'おばあさんが子どもたちに物語を話してくれた。',exampleReading:'おばあさんがこどもたちにものがたりをはなしてくれた。',
   exampleMeaning:'Grandma told the children a story.'},
  {id:'f009',lesson:27,type:'vocab',front:'人形',reading:'にんぎょう',meaning:'doll, puppet',
   example:'日本の人形はとてもきれいです。',exampleReading:'にほんのにんぎょうはとてもきれいです。',
   exampleMeaning:'Japanese dolls are very beautiful.'},
  {id:'f010',lesson:26,type:'vocab',front:'優しい',reading:'やさしい',meaning:'kind, gentle, easy',
   example:'田中先生はとても優しい先生です。',exampleReading:'たなかせんせいはとてもやさしいせんせいです。',
   exampleMeaning:'Tanaka-sensei is a very kind teacher.'},
  {id:'f011',lesson:26,type:'vocab',front:'料理',reading:'りょうり',meaning:'cooking, dish, cuisine',
   example:'母の料理はいつもおいしいです。',exampleReading:'ははのりょうりはいつもおいしいです。',
   exampleMeaning:'My mother\'s cooking is always delicious.'},
  {id:'f012',lesson:27,type:'vocab',front:'教室',reading:'きょうしつ',meaning:'classroom',
   example:'教室に学生が二十人います。',exampleReading:'きょうしつにがくせいがにじゅうにんいます。',
   exampleMeaning:'There are twenty students in the classroom.'},
  {id:'f013',lesson:26,type:'vocab',front:'季節',reading:'きせつ',meaning:'season',
   example:'日本には四つの季節があります。',exampleReading:'にほんにはよっつのきせつがあります。',
   exampleMeaning:'Japan has four seasons.'},
  {id:'f014',lesson:26,type:'vocab',front:'アルバイト',reading:'アルバイト',meaning:'part-time job',
   example:'大学生のとき、カフェでアルバイトをしました。',exampleReading:'だいがくせいのとき、カフェでアルバイトをしました。',
   exampleMeaning:'When I was a university student, I worked part-time at a cafe.'},
  {id:'f015',lesson:26,type:'vocab',front:'おみやげ',reading:'おみやげ',meaning:'souvenir, gift from a trip',
   example:'京都へ行ったとき、おみやげを買いました。',exampleReading:'きょうとへいったとき、おみやげをかいました。',
   exampleMeaning:'When I went to Kyoto, I bought souvenirs.'},
  {id:'f016',lesson:26,type:'vocab',front:'練習',reading:'れんしゅう',meaning:'practice',
   example:'毎日日本語の練習をしています。',exampleReading:'まいにちにほんごのれんしゅうをしています。',
   exampleMeaning:'I practice Japanese every day.'},
  {id:'f017',lesson:27,type:'vocab',front:'急に',reading:'きゅうに',meaning:'suddenly, all of a sudden',
   example:'急に雨が降ってきました。',exampleReading:'きゅうにあめがふってきました。',
   exampleMeaning:'It suddenly started to rain.'},
  {id:'f018',lesson:28,type:'vocab',front:'お見舞い',reading:'おみまい',meaning:'hospital visit, get-well visit',
   example:'入院した友達にお見舞いに行きました。',exampleReading:'にゅういんしたともだちにおみまいにいきました。',
   exampleMeaning:'I visited my hospitalized friend.'},
  {id:'f019',lesson:27,type:'vocab',front:'寂しい',reading:'さびしい',meaning:'lonely, lonesome',
   example:'一人で住んでいると、時々寂しいです。',exampleReading:'ひとりでそんでいると、ときどきさびしいです。',
   exampleMeaning:'Living alone, I sometimes feel lonely.'},
  {id:'f020',lesson:26,type:'vocab',front:'自分',reading:'じぶん',meaning:'oneself, myself',
   example:'自分で料理を作るのは楽しいです。',exampleReading:'じぶんでりょうりをつくるのはたのしいです。',
   exampleMeaning:'It\'s fun to cook for yourself.'},
  // Grammar flashcards
  {id:'f021',lesson:26,type:'grammar',front:'〜てあげる',reading:'〜てあげる',meaning:'to do something for someone (you give)',
   example:'友達に日本語を教えてあげました。',exampleReading:'ともだちににほんごをおしえてあげました。',
   exampleMeaning:'I taught Japanese to my friend (as a favor).'},
  {id:'f022',lesson:26,type:'grammar',front:'〜てくれる',reading:'〜てくれる',meaning:'someone does something for me (they give)',
   example:'先生が漢字を説明してくれました。',exampleReading:'せんせいがかんじをせつめいしてくれました。',
   exampleMeaning:'The teacher explained the kanji for me.'},
  {id:'f023',lesson:26,type:'grammar',front:'〜てもらう',reading:'〜てもらう',meaning:'to receive the favor of someone doing something',
   example:'母に弁当を作ってもらいました。',exampleReading:'ははにべんとうをつくってもらいました。',
   exampleMeaning:'I had my mother make me a bento.'},
  {id:'f024',lesson:27,type:'grammar',front:'〜てしまう',reading:'〜てしまう',meaning:'to do completely / accidentally (with regret)',
   example:'宿題を忘れてしまいました。',exampleReading:'しゅくだいをわすれてしまいました。',
   exampleMeaning:'I accidentally forgot my homework.'},
  {id:'f025',lesson:28,type:'grammar',front:'〜ておく',reading:'〜ておく',meaning:'to do in advance / leave in a state',
   example:'旅行の前にホテルを予約しておきます。',exampleReading:'りょこうのまえにホテルをよやくしておきます。',
   exampleMeaning:'I\'ll book the hotel in advance before the trip.'},
  {id:'f026',lesson:27,type:'grammar',front:'〜てみる',reading:'〜てみる',meaning:'to try doing something',
   example:'新しいレストランで食べてみました。',exampleReading:'あたらしいレストランでたべてみました。',
   exampleMeaning:'I tried eating at the new restaurant.'},
  {id:'f027',lesson:28,type:'grammar',front:'〜ているところ',reading:'〜ているところ',meaning:'in the middle of doing (right now)',
   example:'今、ちょうど料理しているところです。',exampleReading:'いま、ちょうどりょうりしているところです。',
   exampleMeaning:'I\'m right in the middle of cooking now.'},
  {id:'f028',lesson:28,type:'grammar',front:'〜たばかり',reading:'〜たばかり',meaning:'just did something (very recently)',
   example:'日本語の勉強を始めたばかりです。',exampleReading:'にほんごのべんきょうをはじめたばかりです。',
   exampleMeaning:'I just started studying Japanese.'},
  {id:'f029',lesson:28,type:'grammar',front:'〜まま',reading:'〜まま',meaning:'leaving something in a state / as is',
   example:'電気をつけたまま寝てしまいました。',exampleReading:'でんきをつけたままねてしまいました。',
   exampleMeaning:'I fell asleep with the lights still on.'},
  {id:'f030',lesson:27,type:'grammar',front:'potential form',reading:'〜られる / 〜える',meaning:'can do / be able to do',
   example:'ひらがなが読めるようになりました。',exampleReading:'ひらがながよめるようになりました。',
   exampleMeaning:'I became able to read hiragana.'},
];

const LESSONS = [
  {id:'l026',number:26,title:'Lesson 26 — てあげる/くれる/もらう',questionCount:0,flashcardCount:0},
  {id:'l027',number:27,title:'Lesson 27 — てしまう / てみる',questionCount:0,flashcardCount:0},
  {id:'l028',number:28,title:'Lesson 28 — ておく / たばかり / まま',questionCount:0,flashcardCount:0},
];

export default async function handler(req, res) {
  // Only allow GET (no auth needed since it's a one-time setup)
  // Add a secret param to avoid accidental re-runs
  if (req.query.secret !== 'seed_nihongo_2024') {
    return res.status(400).json({ ok: false, error: 'Missing secret param. Add ?secret=seed_nihongo_2024 to the URL' });
  }

  if (!UPSTASH_URL || !UPSTASH_TOKEN) {
    return res.status(500).json({ ok: false, error: 'Upstash env vars not set' });
  }

  try {
    await redisSet('questions', QUESTIONS);
    await redisSet('flashcards', FLASHCARDS);
    await redisSet('lessons', LESSONS);

    return res.status(200).json({
      ok: true,
      message: 'Database seeded successfully!',
      counts: {
        questions: QUESTIONS.length,
        flashcards: FLASHCARDS.length,
        lessons: LESSONS.length,
      }
    });
  } catch (err) {
    return res.status(500).json({ ok: false, error: err.message });
  }
}
